version: '3.8'

services:
  db1:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example1
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: