services:
  db1:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: dbUsers
      MYSQL_ROOT_PASSWORD: example1
    ports:
      - "3306:3306"
    volumes:
      - ./DB/init.sql:/docker-entrypoint-initdb/init.sql

  backend:
    build: ./Backend
    restart: always
    ports:
      - "666:666"
    depends_on:
      - db1

  frontend:
    build: ./Frontend
    restart: always
    ports:
      - "777:777"
    depends_on:
      - backend
